version: "3.9"
services:
  random-player:
    build: .
    environment: 
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    command: ["python", "src/battler/deploy/random_player.py"]

  base-player:
    build: .
    environment: 
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    command: ["python", "src/battler/deploy/base_player.py"]

  dqn-player:
    build: .
    environment: 
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    command: ["python", "src/battler/deploy/dqn_player.py"]

  train-ppo:
    build: .
    environment: 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      MLFOW_TRACKING_URI: ${MLFOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
    volumes:
      - .:/app
    working_dir: /app
    command: ["kedro", "run", "--pipeline", "ppo"]