epochs: 100
lightning_kwargs:
    replay_size: 100_000
    warm_start_steps: 10_000
    gamma: 0.99
    eps_start: 1.0
    eps_end: 0.05
    eps_last_frame: 300_000
    sync_rate: 100
    lr: 0.0003 
    episode_length: 10_000
    batch_size: 32
    stack_length: 8
checkpoint_path: 'data/06_models/ckpt'
loss_type: mse
# TODO inject loss function

train_opponent: max_damage
obs_space: 16

random_opponent: random
max_opponent: max_damage
self_opponent: self
n_battles: 200

battle_format: gen7randombattle
observation_space: 108

dqn_kwargs:
    hidden_size: 128
    num_layers: 2
    stack_size: 8
    #num_heads: 1

rl_player_kwargs:
    obs_space: 16
    fainted_value: 2
    hp_value: 1
    #number_of_pokemons: 6
    #starting_value: 0.0
    status_value: 0.0
    victory_value: 30

#opponent_name: random
#oppoennt