epochs: 4_000
lightning_kwargs:
    replay_size: 100_000
    warm_start_steps: 20_000
    gamma: 0.99
    eps_start: 1.0
    eps_end: 0.01
    eps_last_frame: 100_000  
    sync_rate: 1_000
    lr: 0.0003 
    # how many samples per epoch
    episode_length: 3_200  # episode_length / batch_size = iters/ (steps per epoch)
    batch_size: 32
    stack_length: 4
    n_battles: 200
checkpoint_path: 'data/06_models/ckpt'
loss_type: mse
# TODO inject loss function

train_opponent: max_damage
obs_space: 16
n_battles: 200

random_opponent: random
max_opponent: max_damage
self_opponent: self

battle_format: gen7randombattle
observation_space: 108

dqn_kwargs:
    hidden_size: 128
    stack_size: 4
    num_layers: 3
    out_channels: 1
    #num_heads: 1

rl_player_kwargs:
    obs_space: 16
    fainted_value: 2
    hp_value: 1
    #number_of_pokemons: 6
    #starting_value: 0.0
    status_value: 0.0
    victory_value: 30

#opponent_name: random
#oppoennt