epochs: 1000
lightning_kwargs:

    replay_size: 1_000_000
    warm_start_steps: 2_000
    gamma: 0.97
    eps_start: 1.0
    eps_end: 0.01
    eps_last_frame: 1000_000  
    sync_rate: 10000
    lr: 0.0003 
    # how many samples per epoch
    episode_length: 1_600  # episode_length / batch_size = iters/ (steps per epoch)
    batch_size: 32
    n_battles: 400
    eval_interval: 100
    #obs_space: 1289
    #opponent_type: self
checkpoint_path: 'data/06_models/ckpt'
loss_type: mse
# TODO inject loss function


# TODO pass gpu/trainer kwargs
ppo_lightning_kwargs:
    env_name: Pokemon-v8
    gamma: 0.95
    lam: 0.95
    lr_actor: 3.0E-4
    lr_critic: 1.0E-3
    max_episode_len: 100
    batch_size: 512
    #batch_size: int = 1024,
    steps_per_epoch: 4096 # increased due to randomness of pokes
    #steps_per_epoch: int = 8192, # increased due to randomness of pokes
    nb_optim_iters: 4
    clip_ratio: 0.2
    n_policies: 100
    policy_update_threshold: 0.6

    net_kwargs:
        hidden_dim: 256
        num_dense_layers: 2

    env_kwargs:
        stack_size: 64
        obs_space: 1289
        battle_format: gen8randombattle
        reward_kwargs:
            fainted_value: 1.  # makes the agent really want to keep alive
            # it might be less likely to sacrifice a pokemon even if it makes it more likely to win
            hp_value: 1.  # makes the agent really want to keep alive
            #number_of_pokemons: 6
            #starting_value: 0.0
            status_value: 0.2
            victory_value: 6.

trainer_kwargs:
  gpus: 1
  accelerator: 'dp'
  max_epochs: 10000
  flush_logs_every_n_steps: 4000


blessing_n_battles: 200

random_opponent: random
max_opponent: max_damage
self_opponent: self

observation_space: 108

dqn_kwargs:
    obs_size: 66
    n_actions: 17
    hidden_size: 128
    stack_size: 1
    num_layers: 2
    out_channels: 4
    #num_heads: 1

rl_player_kwargs:
    reward_kwargs:
        fainted_value: 0.1  # makes the agent really want to keep alive
        # it might be less likely to sacrifice a pokemon even if it makes it more likely to win
        hp_value: 0  # makes the agent really want to keep alive
        #number_of_pokemons: 6
        #starting_value: 0.0
        status_value: 0.02
        victory_value: 1

#opponent_name: random
#oppoennt