name: Deploy Base Agent

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    concurrency: pokemon-battler-dqn
    # The type of runner that the job will run on
    runs-on: [self-hosted,deploy,4c]

    env:
      USERNAME: ${{ secrets.DQN_USERNAME }}
      PASSWORD: ${{ secrets.DQN_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: docker-compose up --build -d --remove-orphans --force-recreate dqn-player